/**
 * Theme Component Categories — Fully Region-Isolated
 *
 * ZERO cross-region contamination. Changing any variable in one
 * category will NEVER affect elements in another category.
 *
 * Each region has its own scoped CSS variables that default to
 * the global values but can be overridden independently.
 */
export const THEME_COMPONENT_CATEGORIES = [
  {
    id: 'background_central',
    name: '🏠 Background & Central Workspace',
    description: 'The main page background, overlay, home panel, upload dropzone, user identity, footer — everything behind the windows. Isolated from sidebar, windows, dock, and right panel.',
    tokens: [
      // === Page Background ===
      { key: '--app-bg', label: 'Page Background', type: 'color', default: '#f6efea' },
      { key: '--linkx-shell-bg-solid', label: 'Shell Solid Fill', type: 'color', default: '#f6efea' },
      { key: '--central-overlay-bg', label: 'Overlay Backdrop (expanded launcher)', type: 'color', default: 'rgba(0, 0, 0, 0.35)' },
      // === Background Overlay Gradient ===
      { key: '--central-overlay-top', label: '🎨 Overlay — Top Color', type: 'color', default: '#f6efea' },
      { key: '--central-overlay-mid', label: '🎨 Overlay — Middle Color', type: 'color', default: 'rgba(19, 30, 42, 0.88)' },
      { key: '--central-overlay-bottom', label: '🎨 Overlay — Bottom Color', type: 'color', default: '#f6efea' },
      { key: '--central-overlay-angle', label: '📐 Overlay — Gradient Angle/Direction', type: 'text', default: '180deg' },
      { key: '--central-overlay-opacity', label: '🎨 Overlay — Opacity', type: 'range', default: '1' },

      // === 🖼️ Home Panel Background & Gradient ===
      { key: '--central-panel-gradient-top', label: '🖼️ Home Panel — Gradient Top Color', type: 'color', default: 'rgba(255, 255, 255, 0.96)' },
      { key: '--central-panel-gradient-bottom', label: '🖼️ Home Panel — Gradient Bottom Color', type: 'color', default: 'rgba(246, 239, 234, 0.96)' },
      { key: '--central-panel-gradient-angle', label: '📐 Home Panel — Gradient Angle/Direction', type: 'text', default: '180deg' },
      { key: '--central-panel-bg-custom', label: '🖼️ Home Panel — Custom Solid Fill (Overrides Gradient)', type: 'color', default: '' },
      { key: '--central-panel-border', label: 'Home Panel Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-panel-shadow', label: 'Home Panel Shadow', type: 'color', default: 'rgba(0, 0, 0, 0.15)' },
      { key: '--central-expanded-panel-gradient-top', label: '🖼️ Expanded Panel — Gradient Top Color', type: 'color', default: 'rgba(255, 255, 255, 0.98)' },
      { key: '--central-expanded-panel-gradient-bottom', label: '🖼️ Expanded Panel — Gradient Bottom Color', type: 'color', default: 'rgba(246, 239, 234, 0.98)' },
      { key: '--central-expanded-panel-gradient-angle', label: '📐 Expanded Panel — Gradient Angle/Direction', type: 'text', default: '180deg' },
      { key: '--central-expanded-panel-bg-custom', label: '🖼️ Expanded Panel — Custom Solid/CSS Fill', type: 'color', default: '' },
      { key: '--central-expanded-panel-border', label: '🖼️ Expanded Panel — Border Color', type: 'color', default: 'rgba(174, 135, 79, 0.55)' },

      // === ✏️ Decoupled Text & Component Colors ===
      { key: '--central-home-title-color', label: '🏷️ Home Title Text ("File upload")', type: 'color', default: '#131e2a' },
      { key: '--central-home-subtitle-color', label: '📝 Home Panel Subtitle ("Drop files...")', type: 'color', default: '#ae874f' },
      { key: '--central-identity-text', label: '👤 Username Text (Top-Left)', type: 'color', default: '#131e2a' },
      { key: '--central-footer-text-color', label: '📄 Footer Text & Link Color', type: 'color', default: '#7f5523' },

      // === 📥 File Upload Dropzone (Identity-Separated) ===
      { key: '--central-upload-bg', label: '📥 Upload Dropzone — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-upload-border', label: '📥 Upload Dropzone — Dashed Border', type: 'color', default: '#FCC676' },
      { key: '--central-upload-hover-bg', label: '📥 Upload Dropzone — Hover Background', type: 'color', default: 'rgba(252, 198, 118, 0.08)' },
      { key: '--central-upload-hover-border', label: '📥 Upload Dropzone — Hover Border', type: 'color', default: '#FCC676' },
      { key: '--central-upload-mark-bg', label: '📦 Upload Icon Badge BG', type: 'color', default: '#FCC676' },
      { key: '--central-upload-icon-color', label: '📦 Upload SVG Icon Color', type: 'color', default: '#131e2a' },

      // === 🔘 Option Buttons (Identity-Separated) ===
      { key: '--central-option-card-bg', label: '🔘 Option Buttons — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-option-card-border', label: '🔘 Option Buttons — Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-option-text-color', label: '🔘 Option Buttons — Text Color', type: 'color', default: '#7f5523' },
      { key: '--central-option-hover-bg', label: '🔘 Option Buttons — Hover Background', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--central-option-hover-border', label: '🔘 Option Buttons — Hover Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-option-hover-text', label: '🔘 Option Buttons — Hover Text Color', type: 'color', default: '#131e2a' },

      // === 🏷️ Header Badge, Subtitle & Reset Button (Identity-Separated) ===
      { key: '--central-badge-text-color', label: '🏷️ Header Badge — Text Color', type: 'color', default: '#FCC676' },
      { key: '--central-badge-bg', label: '🏷️ Header Badge — Background', type: 'color', default: 'transparent' },
      { key: '--central-badge-border', label: '🏷️ Header Badge — Border', type: 'color', default: 'transparent' },
      { key: '--central-panel-header-subtitle-color', label: '🏷️ Header Subtitle — Text Color', type: 'color', default: '#ae874f' },
      { key: '--central-panel-reset-btn-bg', label: '🔄 Header Reset Button — Background', type: 'color', default: 'transparent' },
      { key: '--central-panel-reset-btn-border', label: '🔄 Header Reset Button — Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--central-panel-reset-btn-text', label: '🔄 Header Reset Button — Icon Color', type: 'color', default: '#ae874f' },
      { key: '--central-panel-reset-btn-hover-bg', label: '🔄 Header Reset Button — Hover Background', type: 'color', default: 'rgba(174, 135, 79, 0.18)' },
      { key: '--central-panel-reset-btn-hover-border', label: '🔄 Header Reset Button — Hover Border', type: 'color', default: '#FCC676' },
      { key: '--central-panel-reset-btn-hover-text', label: '🔄 Header Reset Button — Hover Icon Color', type: 'color', default: '#131e2a' },

      // === ⚡ Analyze Action Button & Config Review (Identity-Separated) ===
      { key: '--central-analyze-btn-label', label: '⚡ Analyze Button — Label Text', type: 'text', default: 'Analyze' },
      { key: '--central-analyze-btn-gradient-top', label: '⚡ Analyze Button — Gradient Top Color', type: 'color', default: '#FCC676' },
      { key: '--central-analyze-btn-gradient-bottom', label: '⚡ Analyze Button — Gradient Bottom Color', type: 'color', default: '#fdb84d' },
      { key: '--central-analyze-btn-gradient-angle', label: '📐 Analyze Button — Gradient Angle', type: 'text', default: '135deg' },
      { key: '--central-analyze-btn-bg-custom', label: '⚡ Analyze Button — Custom Solid/CSS Fill', type: 'color', default: '' },
      { key: '--central-analyze-btn-text', label: '⚡ Analyze Button — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-analyze-icon-color', label: '⚡ Analyze Button — Icon Color (Flat White)', type: 'color', default: '#ffffff' },
      { key: '--central-analyze-btn-border', label: '⚡ Analyze Button — Border', type: 'color', default: '#FCC676' },
      { key: '--central-analyze-btn-hover-opacity', label: '⚡ Analyze Button — Hover Opacity', type: 'range', default: '0.85' },
      { key: '--central-analyze-btn-disabled-bg', label: '⚡ Analyze Button — Background (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.12)' },
      { key: '--central-analyze-btn-disabled-border', label: '⚡ Analyze Button — Border (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.15)' },
      { key: '--central-analyze-btn-disabled-text', label: '⚡ Analyze Button — Text Color (Disabled)', type: 'color', default: 'rgba(148, 163, 184, 0.9)' },

      // === ⏳ Active "Analyzing..." State Button (Identity-Separated) ===
      { key: '--central-analyzing-active-label', label: '⏳ Analyzing Button (Active) — Label Text', type: 'text', default: 'Analyzing' },
      { key: '--central-analyzing-active-gradient-top', label: '⏳ Analyzing Button (Active) — Gradient Top Color', type: 'color', default: '#FCC676' },
      { key: '--central-analyzing-active-gradient-bottom', label: '⏳ Analyzing Button (Active) — Gradient Bottom Color', type: 'color', default: '#e5a845' },
      { key: '--central-analyzing-active-gradient-angle', label: '📐 Analyzing Button (Active) — Gradient Angle', type: 'text', default: '135deg' },
      { key: '--central-analyzing-active-bg-custom', label: '⏳ Analyzing Button (Active) — Custom Solid/CSS Fill', type: 'color', default: '' },
      { key: '--central-analyzing-active-text-color', label: '⏳ Analyzing Button (Active) — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-analyzing-active-border-color', label: '⏳ Analyzing Button (Active) — Border Color', type: 'color', default: '#FCC676' },

      // === 🛡️ Full Panel Analysis Cover Overlay (Identity-Separated) ===
      { key: '--central-analysis-overlay-bg', label: '🛡️ Analysis Overlay — Background Fill', type: 'color', default: 'rgba(19, 30, 42, 0.88)' },
      { key: '--central-analysis-overlay-blur', label: '🛡️ Analysis Overlay — Backdrop Blur', type: 'text', default: '10px' },
      { key: '--central-analysis-overlay-title-color', label: '🛡️ Analysis Overlay — Title Text Color', type: 'color', default: '#FCC676' },
      { key: '--central-analysis-overlay-status-color', label: '🛡️ Analysis Overlay — Status Text Color', type: 'color', default: '#f6efea' },
      { key: '--central-overlay-min-btn-bg', label: '➖ Minimize Button — Background', type: 'color', default: 'rgba(255, 255, 255, 0.12)' },
      { key: '--central-overlay-min-btn-text', label: '➖ Minimize Button — Text Color', type: 'color', default: '#ffffff' },
      { key: '--central-overlay-min-btn-border', label: '➖ Minimize Button — Border', type: 'color', default: 'rgba(255, 255, 255, 0.2)' },
      { key: '--central-overlay-min-btn-hover-bg', label: '➖ Minimize Button — Hover BG', type: 'color', default: 'rgba(255, 255, 255, 0.28)' },
      { key: '--central-overlay-close-btn-bg', label: '❌ Close Button — Background', type: 'color', default: 'rgba(255, 255, 255, 0.12)' },
      { key: '--central-overlay-close-btn-text', label: '❌ Close Button — Text Color', type: 'color', default: '#ffffff' },
      { key: '--central-overlay-close-btn-border', label: '❌ Close Button — Border', type: 'color', default: 'rgba(255, 255, 255, 0.2)' },
      { key: '--central-overlay-close-btn-hover-bg', label: '❌ Close Button — Hover BG', type: 'color', default: 'rgba(220, 38, 38, 0.7)' },
      { key: '--central-tasks-badge-bg', label: '📋 Tasks Badge — Background', type: 'color', default: '#FCC676' },
      { key: '--central-tasks-badge-text', label: '📋 Tasks Badge — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-tasks-badge-border', label: '📋 Tasks Badge — Border', type: 'color', default: 'transparent' },
      { key: '--central-reports-badge-bg', label: '📊 Reports Badge — Background', type: 'color', default: '#FCC676' },
      { key: '--central-reports-badge-text', label: '📊 Reports Badge — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-reports-badge-border', label: '📊 Reports Badge — Border', type: 'color', default: 'transparent' },
      { key: '--central-bg-btn-bg', label: '🏃 Run in BG Button — Background', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--central-bg-btn-text', label: '🏃 Run in BG Button — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-bg-btn-border', label: '🏃 Run in BG Button — Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-bg-btn-hover-bg', label: '🏃 Run in BG Button — Hover Background', type: 'color', default: 'rgba(174, 135, 79, 0.18)' },
      { key: '--central-cancel-btn-bg', label: '🚫 Cancel Button — Background', type: 'color', default: 'rgba(220, 38, 38, 0.08)' },
      { key: '--central-cancel-btn-text', label: '🚫 Cancel Button — Text Color', type: 'color', default: '#dc2626' },
      { key: '--central-cancel-btn-border', label: '🚫 Cancel Button — Border', type: 'color', default: 'rgba(220, 38, 38, 0.4)' },
      { key: '--central-cancel-btn-hover-bg', label: '🚫 Cancel Button — Hover Background', type: 'color', default: 'rgba(220, 38, 38, 0.18)' },
      { key: '--central-config-review-bg', label: '⚙️ Review Config — Background', type: 'color', default: 'rgba(0, 0, 0, 0.03)' },
      { key: '--central-config-review-border', label: '⚙️ Review Config — Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },

      // === 📊 Analysis Findings Container (Identity-Separated) ===
      { key: '--central-findings-bg', label: '📊 Findings Container — Background', type: 'color', default: 'rgba(0, 0, 0, 0.03)' },
      { key: '--central-findings-border', label: '📊 Findings Container — Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--central-findings-status-bg', label: '📊 Findings Status Badge — Background', type: 'color', default: 'rgba(220, 38, 38, 0.12)' },
      { key: '--central-findings-status-text', label: '📊 Findings Status Badge — Text Color', type: 'color', default: '#dc2626' },
      { key: '--central-findings-status-border', label: '📊 Findings Status Badge — Border', type: 'color', default: 'rgba(220, 38, 38, 0.3)' },
      { key: '--central-findings-anomaly-bg', label: '📊 Findings Anomaly Tag — Background', type: 'color', default: 'rgba(252, 198, 118, 0.12)' },
      { key: '--central-findings-anomaly-text', label: '📊 Findings Anomaly Tag — Text Color', type: 'color', default: '#7f5523' },
      { key: '--central-findings-anomaly-border', label: '📊 Findings Anomaly Tag — Border', type: 'color', default: 'rgba(252, 198, 118, 0.35)' },
      { key: '--central-gds-card-bg', label: '📊 GDS Card — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-gds-card-border', label: '📊 GDS Card — Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--central-influencer-btn-bg', label: '📊 Influencer Node Button — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-influencer-btn-text', label: '📊 Influencer Node Button — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-influencer-btn-border', label: '📊 Influencer Node Button — Border', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--central-influencer-btn-hover-bg', label: '📊 Influencer Node Button — Hover BG', type: 'color', default: 'rgba(252, 198, 118, 0.15)' },

      // === ⚡ Cover Overlay & Control Buttons ===
      { key: '--central-overlay-min-btn-bg', label: '⚡ Overlay — Minimize Button BG', type: 'color', default: 'rgba(255, 255, 255, 0.12)' },
      { key: '--central-overlay-min-btn-text', label: '⚡ Overlay — Minimize Button Text', type: 'color', default: '#ffffff' },
      { key: '--central-overlay-min-btn-border', label: '⚡ Overlay — Minimize Button Border', type: 'color', default: 'rgba(255, 255, 255, 0.2)' },
      { key: '--central-overlay-min-btn-hover-bg', label: '⚡ Overlay — Minimize Button Hover BG', type: 'color', default: 'rgba(255, 255, 255, 0.28)' },
      { key: '--central-overlay-close-btn-bg', label: '⚡ Overlay — Close Button BG', type: 'color', default: 'rgba(255, 255, 255, 0.12)' },
      { key: '--central-overlay-close-btn-text', label: '⚡ Overlay — Close Button Text', type: 'color', default: '#ffffff' },
      { key: '--central-overlay-close-btn-border', label: '⚡ Overlay — Close Button Border', type: 'color', default: 'rgba(255, 255, 255, 0.2)' },
      { key: '--central-overlay-close-btn-hover-bg', label: '⚡ Overlay — Close Button Hover BG', type: 'color', default: 'rgba(220, 38, 38, 0.7)' },
      { key: '--central-file-remove-bg', label: '📄 File Item — Remove Button BG', type: 'color', default: 'transparent' },
      { key: '--central-file-remove-text', label: '📄 File Item — Remove Button Text', type: 'color', default: '#ae874f' },
      { key: '--central-file-remove-hover-bg', label: '📄 File Item — Remove Button Hover BG', type: 'color', default: 'rgba(220, 38, 38, 0.12)' },
      { key: '--central-file-remove-hover-text', label: '📄 File Item — Remove Button Hover Text', type: 'color', default: '#dc2626' },

      // === 🔘 Findings Action Buttons (Identity-Separated) ===
      { key: '--central-file-item-icon-color', label: '📄 Attached File — Icon Color', type: 'color', default: '#ae874f' },
      { key: '--central-findings-net-btn-bg', label: '🕸️ Explore Network Button — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-findings-net-btn-text', label: '🕸️ Explore Network Button — Text Color', type: 'color', default: '#7f5523' },
      { key: '--central-findings-net-btn-border', label: '🕸️ Explore Network Button — Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-findings-net-btn-hover-bg', label: '🕸️ Explore Network Button — Hover BG', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--central-findings-chart-btn-bg', label: '📈 Explore Chart Button — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-findings-chart-btn-text', label: '📈 Explore Chart Button — Text Color', type: 'color', default: '#7f5523' },
      { key: '--central-findings-chart-btn-border', label: '📈 Explore Chart Button — Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-findings-chart-btn-hover-bg', label: '📈 Explore Chart Button — Hover BG', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--central-findings-drop-btn-bg', label: '🗑️ Drop Analysis Button — Background', type: 'color', default: 'rgba(220, 38, 38, 0.08)' },
      { key: '--central-findings-drop-btn-text', label: '🗑️ Drop Analysis Button — Text Color', type: 'color', default: '#dc2626' },
      { key: '--central-findings-drop-btn-border', label: '🗑️ Drop Analysis Button — Border', type: 'color', default: 'rgba(220, 38, 38, 0.4)' },
      { key: '--central-findings-drop-btn-hover-bg', label: '🗑️ Drop Analysis Button — Hover BG', type: 'color', default: 'rgba(220, 38, 38, 0.18)' },

      // === 📜 Panel Scrollbar Identity Tokens ===
      { key: '--central-scrollbar-track-bg', label: '📜 Panel Scrollbar — Track Background', type: 'color', default: 'transparent' },
      { key: '--central-scrollbar-thumb-bg', label: '📜 Panel Scrollbar — Thumb Color', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--central-scrollbar-thumb-hover-bg', label: '📜 Panel Scrollbar — Thumb Hover Color', type: 'color', default: 'rgba(174, 135, 79, 0.65)' },
      { key: '--central-scrollbar-thumb-border', label: '📜 Panel Scrollbar — Thumb Border', type: 'color', default: 'transparent' },

      // === 🗑️ Drop Confirmation Modal (Identity-Separated) ===
      { key: '--central-drop-modal-overlay-bg', label: '🗑️ Drop Confirm Modal — Overlay BG', type: 'color', default: 'rgba(0, 0, 0, 0.55)' },
      { key: '--central-drop-modal-bg', label: '🗑️ Drop Confirm Modal — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-drop-modal-border', label: '🗑️ Drop Confirm Modal — Border', type: 'color', default: 'rgba(220, 38, 38, 0.35)' },
      { key: '--central-drop-modal-title-color', label: '🗑️ Drop Confirm Modal — Title Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-drop-modal-body-color', label: '🗑️ Drop Confirm Modal — Body Text Color', type: 'color', default: '#4a5568' },
      { key: '--central-drop-modal-cancel-bg', label: '🗑️ Drop Confirm Cancel Button — Background', type: 'color', default: 'rgba(0, 0, 0, 0.05)' },
      { key: '--central-drop-modal-cancel-text', label: '🗑️ Drop Confirm Cancel Button — Text Color', type: 'color', default: '#4a5568' },
      { key: '--central-drop-modal-cancel-border', label: '🗑️ Drop Confirm Cancel Button — Border', type: 'color', default: 'rgba(0, 0, 0, 0.15)' },
      { key: '--central-drop-modal-confirm-bg', label: '🗑️ Drop Confirm Action Button — Background', type: 'color', default: '#dc2626' },
      { key: '--central-drop-modal-confirm-text', label: '🗑️ Drop Confirm Action Button — Text Color', type: 'color', default: '#ffffff' },
      { key: '--central-drop-modal-confirm-border', label: '🗑️ Drop Confirm Action Button — Border', type: 'color', default: '#b91c1c' },

      // === 📡 Real-time & Batch Sub-Menu Buttons (Granular Inactive, Hover & Active Controls) ===
      { key: '--central-realtime-container-bg', label: '📡 Real-time Container — Background', type: 'color', default: 'rgba(0, 0, 0, 0.03)' },
      { key: '--central-realtime-container-border', label: '📡 Real-time Container — Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--central-realtime-card-bg', label: '📡 Real-time Sub Button — Background (Inactive)', type: 'color', default: '#FFFFFF' },
      { key: '--central-realtime-card-hover-bg', label: '📡 Real-time Sub Button — Background (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.12)' },
      { key: '--central-realtime-card-active-bg', label: '📡 Real-time Sub Button — Background (Active)', type: 'color', default: 'rgba(252, 198, 118, 0.25)' },
      { key: '--central-realtime-card-border', label: '📡 Real-time Sub Button — Border (Inactive)', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--central-realtime-card-hover-border', label: '📡 Real-time Sub Button — Border (Hover)', type: 'color', default: '#FCC676' },
      { key: '--central-realtime-card-active-border', label: '📡 Real-time Sub Button — Border (Active)', type: 'color', default: '#fdb84d' },
      { key: '--central-realtime-card-title-color', label: '📡 Real-time Sub Button — Title Text (Inactive)', type: 'color', default: '#131e2a' },
      { key: '--central-realtime-card-hover-title-color', label: '📡 Real-time Sub Button — Title Text (Hover)', type: 'color', default: '#131e2a' },
      { key: '--central-realtime-card-active-title-color', label: '📡 Real-time Sub Button — Title Text (Active)', type: 'color', default: '#0d1520' },
      { key: '--central-realtime-card-body-color', label: '📡 Real-time Sub Button — Body Text (Inactive)', type: 'color', default: '#4a5568' },
      { key: '--central-realtime-card-hover-body-color', label: '📡 Real-time Sub Button — Body Text (Hover)', type: 'color', default: '#4a5568' },
      { key: '--central-realtime-card-active-body-color', label: '📡 Real-time Sub Button — Body Text (Active)', type: 'color', default: '#1a2634' },
      { key: '--central-realtime-card-icon-bg', label: '📡 Real-time Sub Button — Icon BG (Inactive)', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--central-realtime-card-icon-hover-bg', label: '📡 Real-time Sub Button — Icon BG (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.2)' },
      { key: '--central-realtime-card-icon-active-bg', label: '📡 Real-time Sub Button — Icon BG (Active)', type: 'color', default: 'rgba(174, 135, 79, 0.25)' },
      { key: '--central-realtime-card-icon-color', label: '📡 Real-time Sub Button — Icon Color (Inactive)', type: 'color', default: '#ae874f' },
      { key: '--central-realtime-card-icon-hover-color', label: '📡 Real-time Sub Button — Icon Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--central-realtime-card-icon-active-color', label: '📡 Real-time Sub Button — Icon Color (Active)', type: 'color', default: '#131e2a' },
      { key: '--central-realtime-card-disabled-bg', label: '📡 Real-time Sub Button — Background (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.04)' },
      { key: '--central-realtime-card-disabled-border', label: '📡 Real-time Sub Button — Border (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.15)' },
      { key: '--central-realtime-card-disabled-text', label: '📡 Real-time Sub Button — Text Color (Disabled)', type: 'color', default: '#8896a6' },
      { key: '--central-realtime-card-disabled-icon-bg', label: '📡 Real-time Sub Button — Icon BG (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.06)' },
      { key: '--central-realtime-card-disabled-icon-color', label: '📡 Real-time Sub Button — Icon Color (Disabled)', type: 'color', default: '#8896a6' },

      // === 🔘 Source Options Active & Hover Controls ===
      { key: '--central-option-card-bg', label: '🔘 Source Option — Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-option-text-color', label: '🔘 Source Option — Text Color (Inactive)', type: 'color', default: '#7f5523' },
      { key: '--central-option-radio-color', label: '🔘 Source Option — Radio Icon Color (Inactive)', type: 'color', default: '#ae874f' },
      { key: '--central-option-card-border', label: '🔘 Source Option — Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-option-hover-bg', label: '🔘 Source Option — Hover Background', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--central-option-hover-text', label: '🔘 Source Option — Hover Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-option-hover-border', label: '🔘 Source Option — Hover Border', type: 'color', default: 'rgba(174, 135, 79, 0.6)' },
      { key: '--central-option-active-bg', label: '🔘 Source Option (Active) — Background', type: 'color', default: 'rgba(252, 198, 118, 0.18)' },
      { key: '--central-option-active-text', label: '🔘 Source Option (Active) — Text Color', type: 'color', default: '#131e2a' },
      { key: '--central-option-active-border', label: '🔘 Source Option (Active) — Border', type: 'color', default: '#FCC676' },
      { key: '--central-option-active-radio-color', label: '🔘 Source Option (Active) — Radio Icon Color', type: 'color', default: '#131e2a' },
      { key: '--central-option-active-border', label: '🔘 Source Option (Active) — Border', type: 'color', default: '#FCC676' },
      { key: '--central-option-active-radio-color', label: '🔘 Source Option (Active) — Radio Color', type: 'color', default: '#131e2a' },

      // === Canvas & User Avatar ===
      { key: '--central-card-bg', label: 'General Card Background', type: 'color', default: '#FFFFFF' },
      { key: '--central-card-border', label: 'General Card Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--central-separator', label: 'Canvas Borders & Dividers', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--central-avatar-bg', label: 'Avatar Background', type: 'color', default: '#131e2a' },
      { key: '--central-avatar-text', label: 'Avatar Letter Color', type: 'color', default: '#FCC676' },
      { key: '--central-avatar-border', label: 'Avatar Border', type: 'color', default: '#ae874f' },

      // === 🔵 Focus & Disabled ===
      { key: '--central-focus-ring', label: '🔵 Focus — Outline Color', type: 'color', default: 'rgba(252, 198, 118, 0.5)' },
      { key: '--central-disabled-opacity', label: '⬜ Disabled — Opacity', type: 'range', default: '0.62' },

      // === 🕸️ Network Background Animation ===
      { key: '--network-node-color', label: '🕸️ Network — Node Color', type: 'color', default: 'rgba(252, 198, 118, 0.55)' },
      { key: '--network-edge-color', label: '🕸️ Network — Edge Color', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--network-glow-color', label: '🕸️ Network — Glow Color', type: 'color', default: 'rgba(252, 198, 118, 0.08)' },
      { key: '--network-opacity', label: '🕸️ Network — Overall Opacity', type: 'range', default: '0.65' },
    ],
  },
  {
    id: 'right_workspace',
    name: '👉 Right Side — Workspace Board',
    description: 'Customization tokens dedicated to the Right Workspace sidebar, context tabs, telemetry cards, AI assistant, and settings.',
    tokens: [
      // === Right Sidebar Base Background Gradient Controls ===
      { key: '--right-workspace-gradient-top', label: '👉 Right Sidebar — Gradient Top Color', type: 'color', default: 'rgba(255, 255, 255, 0.98)' },
      { key: '--right-workspace-gradient-bottom', label: '👉 Right Sidebar — Gradient Bottom Color', type: 'color', default: 'rgba(246, 239, 234, 0.92)' },
      { key: '--right-workspace-gradient-angle', label: '📐 Right Sidebar — Gradient Angle', type: 'text', default: '180deg' },
      { key: '--right-workspace-bg', label: '👉 Right Sidebar — Custom Solid Fill (Overrides Gradient)', type: 'color', default: '' },
      { key: '--right-workspace-border', label: 'Sidebar Border Line', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },

      // === Context Navigation Tabs & Header Wrapper ===
      { key: '--right-tabs-wrapper-bg', label: 'Header Tabs Wrapper Fill', type: 'color', default: 'transparent' },
      { key: '--right-collapse-btn-bg', label: 'Collapse/Expand Button Fill (Idle)', type: 'color', default: '#FFFFFF' },
      { key: '--right-collapse-btn-border', label: 'Collapse/Expand Button Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--right-collapse-btn-icon', label: 'Collapse/Expand Button Icon Color (Idle)', type: 'color', default: '#8896a6' },
      { key: '--right-collapse-btn-hover-bg', label: 'Collapse/Expand Button Fill (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--right-collapse-btn-hover-border', label: 'Collapse/Expand Button Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--right-collapse-btn-hover-icon', label: 'Collapse/Expand Button Icon Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--right-tabs-bg', label: 'Tabs Bar Background', type: 'color', default: 'rgba(0, 0, 0, 0.04)' },
      { key: '--right-tabs-border', label: 'Tabs Bar Bottom Divider', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--right-tab-text', label: 'Tab Text Color (Inactive)', type: 'color', default: '#8896a6' },
      { key: '--right-tab-hover-bg', label: 'Tab Hover Background', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--right-tab-hover-text', label: 'Tab Hover Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-tab-active-bg', label: 'Tab Active Background', type: 'color', default: 'rgba(252, 198, 118, 0.18)' },
      { key: '--right-tab-active-text', label: 'Tab Active Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-tab-active-border', label: 'Tab Active Accent Line', type: 'color', default: '#FCC676' },

      // === Section Headings & Inner Cards ===
      { key: '--right-card-title-color', label: '🏷️ Card Title Text Color (e.g. Session, Workspace, Activity, Assistant)', type: 'color', default: '#ae874f' },
      { key: '--right-card-toggle-btn-bg', label: 'Card Collapse/Expand Button Fill (Idle)', type: 'color', default: 'transparent' },
      { key: '--right-card-toggle-btn-color', label: 'Card Collapse/Expand Button Icon Color (Idle)', type: 'color', default: '#ae874f' },
      { key: '--right-card-toggle-btn-hover-bg', label: 'Card Collapse/Expand Button Fill (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--right-card-toggle-btn-hover-color', label: 'Card Collapse/Expand Button Icon Color (Hover)', type: 'color', default: '#ae874f' },
      { key: '--right-card-bg', label: 'Inner Section Card Background Color', type: 'color', default: '#FFFFFF' },
      { key: '--right-card-bg-opacity', label: '🎚️ Inner Section Card — Background Opacity (Text stays 100% solid)', type: 'range', default: '0.85' },
      { key: '--right-card-border', label: 'Inner Section Card Border', type: 'color', default: 'rgba(174, 135, 79, 0.25)' },
      { key: '--right-label-color', label: '📌 Data Label Text Color (e.g. Signed in as, Status, Open windows)', type: 'color', default: '#7f5523' },
      { key: '--right-value-color', label: '💬 Data Value Text Color (e.g. Analyst, Active, None)', type: 'color', default: '#131e2a' },
      { key: '--right-status-badge-bg', label: 'Session Active Badge Background', type: 'color', default: 'rgba(16, 185, 129, 0.15)' },
      { key: '--right-status-badge-text', label: 'Session Active Badge Text Color', type: 'color', default: '#059669' },
      { key: '--right-empty-text-color', label: 'Empty State Placeholder Text Color', type: 'color', default: '#8896a6' },

      // === AI Assistant Chat Panel & Conversations ===
      { key: '--right-chat-bg', label: 'Assistant Card Fill', type: 'color', default: '#FFFFFF' },
      { key: '--right-chat-border', label: 'Assistant Card Border Line', type: 'color', default: 'rgba(174, 135, 79, 0.25)' },
      { key: '--right-assistant-action-btn-bg', label: 'Assistant Header Action Button Fill (Idle)', type: 'color', default: 'transparent' },
      { key: '--right-assistant-action-btn-color', label: 'Assistant Header Action Button Icon Color (Idle)', type: 'color', default: '#ae874f' },
      { key: '--right-assistant-action-btn-hover-bg', label: 'Assistant Header Action Button Fill (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--right-assistant-action-btn-hover-color', label: 'Assistant Header Action Button Icon Color (Hover)', type: 'color', default: '#ae874f' },
      { key: '--right-chat-avatar-bg', label: 'Chat Avatar Background Fill', type: 'color', default: 'rgba(174, 135, 79, 0.15)' },
      { key: '--right-chat-avatar-text', label: 'Chat Avatar Icon/Text Color', type: 'color', default: '#ae874f' },
      { key: '--right-chat-user-msg-bg', label: 'User Chat Message Bubble Fill', type: 'color', default: 'rgba(252, 198, 118, 0.22)' },
      { key: '--right-chat-user-msg-border', label: 'User Chat Message Bubble Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--right-chat-user-msg-text', label: 'User Chat Message Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-chat-user-msg-time', label: 'User Chat Timestamp Color', type: 'color', default: '#8896a6' },
      { key: '--right-chat-assistant-msg-bg', label: 'Assistant Chat Message Bubble Fill', type: 'color', default: 'rgba(0, 0, 0, 0.04)' },
      { key: '--right-chat-assistant-msg-border', label: 'Assistant Chat Message Bubble Border', type: 'color', default: 'rgba(174, 135, 79, 0.22)' },
      { key: '--right-chat-assistant-msg-text', label: 'Assistant Chat Message Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-chat-assistant-msg-time', label: 'Assistant Chat Timestamp Color', type: 'color', default: '#8896a6' },
      { key: '--right-chat-thinking-bg', label: 'Thinking Bubble Background Fill', type: 'color', default: 'rgba(0, 0, 0, 0.04)' },
      { key: '--right-chat-thinking-border', label: 'Thinking Bubble Border Line', type: 'color', default: 'rgba(174, 135, 79, 0.22)' },
      { key: '--right-chat-thinking-dot-color', label: 'Thinking Dots Pulsing Color', type: 'color', default: '#ae874f' },
      { key: '--right-chat-prompt-bg', label: 'Quick Prompt Pill Fill (Idle)', type: 'color', default: 'rgba(252, 198, 118, 0.15)' },
      { key: '--right-chat-prompt-border', label: 'Quick Prompt Pill Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--right-chat-prompt-text', label: 'Quick Prompt Pill Text Color (Idle)', type: 'color', default: '#7f5523' },
      { key: '--right-chat-prompt-hover-bg', label: 'Quick Prompt Pill Fill (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.35)' },
      { key: '--right-chat-prompt-hover-border', label: 'Quick Prompt Pill Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.6)' },
      { key: '--right-chat-prompt-hover-text', label: 'Quick Prompt Pill Text Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--right-chat-bubble-action-color', label: 'Message Hover Action Icon Color (Idle)', type: 'color', default: '#ae874f' },
      { key: '--right-chat-bubble-action-hover-bg', label: 'Message Hover Action Button Background (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.14)' },
      { key: '--right-chat-bubble-action-hover-color', label: 'Message Hover Action Icon Color (Hover)', type: 'color', default: '#ae874f' },
      { key: '--right-chat-input-bg', label: 'Assistant Input Field Background (Idle)', type: 'color', default: '#FFFFFF' },
      { key: '--right-chat-input-focus-bg', label: 'Assistant Input Field Background (Focus)', type: 'color', default: '#FFFFFF' },
      { key: '--right-chat-input-border', label: 'Assistant Input Field Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--right-chat-input-text', label: 'Assistant Input Typed Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-chat-input-placeholder', label: 'Assistant Input Placeholder Color', type: 'color', default: '#8896a6' },
      { key: '--right-chat-word-counter-color', label: 'Input Word Counter Text Color', type: 'color', default: '#8896a6' },
      { key: '--right-chat-input-focus-border', label: 'Assistant Input Focused Border', type: 'color', default: '#FCC676' },
      { key: '--right-chat-input-focus-ring', label: 'Assistant Input Glow Ring Color', type: 'color', default: 'rgba(252, 198, 118, 0.25)' },
      { key: '--right-chat-send-btn-bg', label: 'Assistant Send Button Fill (Idle)', type: 'color', default: 'rgba(252, 198, 118, 0.35)' },
      { key: '--right-chat-send-btn-border', label: 'Assistant Send Button Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--right-chat-send-btn-icon', label: 'Assistant Send Button Icon Color (Idle)', type: 'color', default: '#131e2a' },
      { key: '--right-chat-send-btn-hover-bg', label: 'Assistant Send Button Fill (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.65)' },
      { key: '--right-chat-send-btn-hover-border', label: 'Assistant Send Button Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.6)' },
      { key: '--right-chat-send-btn-hover-icon', label: 'Assistant Send Button Icon Color (Hover)', type: 'color', default: '#0d1520' },
      { key: '--right-chat-send-btn-disabled-bg', label: 'Assistant Send Button Fill (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.05)' },
      { key: '--right-chat-send-btn-disabled-border', label: 'Assistant Send Button Border (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.1)' },
      { key: '--right-chat-send-btn-disabled-icon', label: 'Assistant Send Button Icon Color (Disabled)', type: 'color', default: '#a0aec0' },
      { key: '--right-chat-stop-btn-bg', label: 'Assistant Stop Button Fill (Idle)', type: 'color', default: 'rgba(239, 68, 68, 0.15)' },
      { key: '--right-chat-stop-btn-border', label: 'Assistant Stop Button Border (Idle)', type: 'color', default: 'rgba(239, 68, 68, 0.4)' },
      { key: '--right-chat-stop-btn-color', label: 'Assistant Stop Button Icon Color (Idle)', type: 'color', default: '#ef4444' },
      { key: '--right-chat-stop-btn-hover-bg', label: 'Assistant Stop Button Fill (Hover)', type: 'color', default: 'rgba(239, 68, 68, 0.28)' },
      { key: '--right-chat-stop-btn-hover-border', label: 'Assistant Stop Button Border (Hover)', type: 'color', default: 'rgba(239, 68, 68, 0.6)' },
      { key: '--right-chat-stop-btn-hover-color', label: 'Assistant Stop Button Icon Color (Hover)', type: 'color', default: '#dc2626' },
      { key: '--right-chat-scroll-btn-bg', label: 'Scroll Down Button Fill (Idle)', type: 'color', default: 'rgba(255, 255, 255, 0.85)' },
      { key: '--right-chat-scroll-btn-border', label: 'Scroll Down Button Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--right-chat-scroll-btn-color', label: 'Scroll Down Button Icon Color (Idle)', type: 'color', default: '#ae874f' },
      { key: '--right-chat-scroll-btn-hover-bg', label: 'Scroll Down Button Fill (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.45)' },
      { key: '--right-chat-scroll-btn-hover-border', label: 'Scroll Down Button Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.6)' },
      { key: '--right-chat-scroll-btn-hover-color', label: 'Scroll Down Button Icon Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--right-chat-scroll-btn-opacity', label: 'Scroll Down Button Opacity (Idle)', type: 'text', default: '0.55' },
      { key: '--right-chat-scroll-btn-hover-opacity', label: 'Scroll Down Button Opacity (Hover)', type: 'text', default: '1' },

      // === Right Workspace Collapsed Strip (Matches Left Sidebar Navigation) ===
      { key: '--right-collapsed-bg', label: 'Right Collapsed Strip Background / Gradient', type: 'color', default: 'var(--linkx-launcher-bg)' },
      { key: '--right-collapsed-border', label: 'Right Collapsed Strip Border', type: 'color', default: 'var(--linkx-launcher-border)' },
      { key: '--right-collapsed-btn-bg', label: 'Right Collapsed Button Background (Idle)', type: 'color', default: 'transparent' },
      { key: '--right-collapsed-btn-border', label: 'Right Collapsed Button Border (Idle)', type: 'color', default: 'transparent' },
      { key: '--right-collapsed-btn-icon', label: 'Right Collapsed Button Icon Color (Idle)', type: 'color', default: '#8896a6' },
      { key: '--right-collapsed-btn-hover-bg', label: 'Right Collapsed Button Background (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--right-collapsed-btn-hover-border', label: 'Right Collapsed Button Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--right-collapsed-btn-hover-icon', label: 'Right Collapsed Button Icon Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--right-collapsed-btn-active-bg', label: 'Right Collapsed Button Background (Active)', type: 'color', default: 'rgba(252, 198, 118, 0.35)' },
      { key: '--right-collapsed-btn-active-border', label: 'Right Collapsed Button Border (Active)', type: 'color', default: '#FCC676' },
      { key: '--right-collapsed-btn-active-icon', label: 'Right Collapsed Button Icon Color (Active)', type: 'color', default: '#131e2a' },

      // === Right Workspace Disabled State Options ===
      { key: '--right-disabled-bg', label: 'Right Panel Background (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.03)' },
      { key: '--right-disabled-border', label: 'Right Panel Border (Disabled)', type: 'color', default: 'rgba(0, 0, 0, 0.12)' },
      { key: '--right-disabled-opacity', label: 'Right Panel Opacity (Disabled)', type: 'text', default: '0.45' },
      { key: '--right-disabled-icon-color', label: 'Tab Icons Color (Disabled)', type: 'color', default: '#94a3b8' },
      { key: '--right-disabled-icon-opacity', label: 'Tab Icons Opacity (Disabled)', type: 'text', default: '0.7' },
      { key: '--right-disabled-tab-bg', label: 'Tab Button Background (Disabled)', type: 'color', default: 'transparent' },
      { key: '--right-disabled-tab-border', label: 'Tab Button Border (Disabled)', type: 'color', default: 'transparent' },

      // === Graph Info & Filter Form Controls ===
      { key: '--right-form-label-color', label: 'Form Control Label Text Color', type: 'color', default: '#4a5568' },
      { key: '--right-form-input-text', label: 'Form Input & Select Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-filter-input-bg', label: 'Filter Form Input Background', type: 'color', default: '#FFFFFF' },
      { key: '--right-filter-input-border', label: 'Filter Form Input Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--right-filter-btn-bg', label: 'Apply Filter Button Background', type: 'color', default: '#FCC676' },
      { key: '--right-filter-btn-text', label: 'Apply Filter Button Text Color', type: 'color', default: '#131e2a' },

      // === Appearance & Theme Studio Options ===
      { key: '--right-theme-option-bg', label: 'Theme Picker Option Background', type: 'color', default: '#FFFFFF' },
      { key: '--right-theme-option-border', label: 'Theme Picker Option Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--right-theme-option-active-bg', label: 'Theme Picker Option (Active) BG', type: 'color', default: 'rgba(252, 198, 118, 0.15)' },
      { key: '--right-theme-option-active-border', label: 'Theme Picker Option (Active) Border', type: 'color', default: '#FCC676' },
      { key: '--right-theme-card-name-color', label: 'Theme Card Name Text Color', type: 'color', default: '#131e2a' },
      { key: '--right-theme-card-badge-text', label: 'Theme Active Badge Text Color', type: 'color', default: '#059669' },
      { key: '--right-theme-card-desc-color', label: 'Theme Description Text Color', type: 'color', default: '#4a5568' },
    ],
  },
  {
    id: 'left_launcher',
    name: '🧭 Left Side — Launcher Rail',
    description: 'Isolated to the left nav rail only. Zero effect on windows, dock, or right panel.',
    tokens: [
      // === Backgrounds ===
      { key: '--linkx-launcher-bg', label: 'Rail Background', type: 'color', default: 'rgba(255, 255, 255, 0.95)' },
      { key: '--linkx-launcher-border', label: 'Rail Outer Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--launcher-shell-bg', label: 'Dropdown Menu Background', type: 'color', default: '#f6efea' },
      { key: '--launcher-border', label: 'Dropdown Menu Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      // === Idle Text ===
      { key: '--launcher-text', label: 'Primary Text (icons, active labels)', type: 'color', default: '#131e2a' },
      { key: '--launcher-text-secondary', label: 'Secondary Text (labels, subtitles)', type: 'color', default: '#7f5523' },
      // === Idle Buttons ===
      { key: '--launcher-item-idle-bg', label: 'Button Idle Background', type: 'color', default: 'transparent' },
      { key: '--launcher-item-idle-border', label: 'Button Idle Border', type: 'color', default: 'transparent' },
      { key: '--launcher-separator', label: 'Dividers & Section Borders', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      // === Hover State ===
      { key: '--launcher-hover-bg', label: '🔹 Hover — Background', type: 'color', default: 'rgba(174, 135, 79, 0.08)' },
      { key: '--launcher-hover-border', label: '🔹 Hover — Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--launcher-hover-text', label: '🔹 Hover — Text Color', type: 'color', default: '#131e2a' },
      // === Active / Pressed State ===
      { key: '--launcher-active-bg', label: '🔸 Active — Background', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--launcher-active-border', label: '🔸 Active — Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--launcher-active-text', label: '🔸 Active — Text Color', type: 'color', default: '#131e2a' },
      // === Focus Ring ===
      { key: '--launcher-focus-ring', label: '🔵 Focus — Outline Color', type: 'color', default: 'rgba(252, 198, 118, 0.5)' },
      // === Disabled ===
      { key: '--launcher-disabled-opacity', label: '⬜ Disabled — Opacity', type: 'range', default: '0.35' },
      // === Misc ===
      { key: '--launcher-highlight', label: 'Legacy Highlight Fill', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
    ],
  },
  {
    id: 'floating_windows',
    name: '🪟 Central Workspace — Floating Windows',
    description: 'Head-to-toe comprehensive design tokens for floating workspace windows: frame, header, title, buttons, body, cards, and resizers.',
    tokens: [
      // === Window Frame & Elevation ===
      { key: '--linkx-window-bg', label: 'Window Outer Frame Fill (Idle)', type: 'color', default: 'rgba(255, 255, 255, 0.96)' },
      { key: '--linkx-window-bg-active', label: 'Window Outer Frame Fill (Active / Focused)', type: 'color', default: 'rgba(255, 255, 255, 0.99)' },
      { key: '--linkx-window-border', label: 'Window Outer Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--linkx-window-border-active', label: 'Window Outer Border (Active / Focused)', type: 'color', default: '#FCC676' },
      { key: '--linkx-window-radius', label: 'Window Corner Radius', type: 'text', default: '6px' },
      { key: '--linkx-window-shadow', label: 'Window Elevation Shadow (Focused)', type: 'text', default: '0 14px 48px rgba(19, 30, 42, 0.16)' },
      { key: '--linkx-window-backdrop-blur', label: 'Window Backdrop Glass Blur', type: 'text', default: '20px' },

      // === Window Header Bar & Drag Handle ===
      { key: '--linkx-window-header-bg', label: 'Header Bar Fill (Idle)', type: 'color', default: '#131e2a' },
      { key: '--linkx-window-header-active-bg', label: 'Header Bar Fill (Active / Focused)', type: 'color', default: '#1f2d3d' },
      { key: '--linkx-window-header-drag-bg', label: 'Header Bar Fill (Dragging)', type: 'color', default: '#2b3d52' },
      { key: '--linkx-window-header-border-bottom', label: 'Header Bar Bottom Border', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--window-header-text', label: 'Header Title Text Color', type: 'color', default: '#FCC676' },
      { key: '--window-header-title-size', label: 'Header Title Font Size', type: 'text', default: '14px' },
      { key: '--window-header-title-weight', label: 'Header Title Font Weight', type: 'text', default: '700' },

      // === Subtitle & Custom Title Input ===
      { key: '--window-subtitle-text', label: 'Custom Title Input Text (Idle)', type: 'color', default: '#8896a6' },
      { key: '--window-subtitle-hover-text', label: 'Custom Title Input Text (Hover / Focus)', type: 'color', default: '#FCC676' },
      { key: '--window-subtitle-border', label: 'Custom Title Input Border (Focus)', type: 'color', default: '#FCC676' },
      { key: '--linkx-input-placeholder', label: 'Custom Title Input Placeholder', type: 'color', default: '#64748b' },

      // === Window Control Action Buttons ===
      { key: '--window-action-btn-bg', label: 'Control Buttons Fill (Idle)', type: 'color', default: 'rgba(255, 255, 255, 0.08)' },
      { key: '--window-action-btn-border', label: 'Control Buttons Border (Idle)', type: 'color', default: 'rgba(255, 255, 255, 0.15)' },
      { key: '--window-action-btn-icon', label: 'Control Buttons Icon Color (Idle)', type: 'color', default: '#8896a6' },
      { key: '--window-action-btn-hover-bg', label: 'Control Buttons Fill (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.25)' },
      { key: '--window-action-btn-hover-border', label: 'Control Buttons Border (Hover)', type: 'color', default: '#FCC676' },
      { key: '--window-action-btn-hover-icon', label: 'Control Buttons Icon Color (Hover)', type: 'color', default: '#131e2a' },

      // === Close Button (Danger State) ===
      { key: '--window-danger-bg', label: 'Close Button Fill (Idle)', type: 'color', default: 'rgba(239, 68, 68, 0.15)' },
      { key: '--window-danger-border', label: 'Close Button Border (Idle)', type: 'color', default: 'rgba(239, 68, 68, 0.35)' },
      { key: '--window-danger-icon', label: 'Close Button Icon Color (Idle)', type: 'color', default: '#ef4444' },
      { key: '--window-danger-hover-bg', label: 'Close Button Fill (Hover)', type: 'color', default: 'rgba(239, 68, 68, 0.35)' },
      { key: '--window-danger-hover-border', label: 'Close Button Border (Hover)', type: 'color', default: '#ef4444' },
      { key: '--window-danger-hover-icon', label: 'Close Button Icon Color (Hover)', type: 'color', default: '#ffffff' },

      // === Window Body & Content Canvas ===
      { key: '--linkx-window-body-bg', label: 'Window Body Canvas Fill', type: 'color', default: 'rgba(255, 255, 255, 0.96)' },
      { key: '--window-text', label: 'Body Primary Text Color', type: 'color', default: '#131e2a' },
      { key: '--window-text-secondary', label: 'Body Secondary Text Color', type: 'color', default: '#4a5568' },
      { key: '--window-text-muted', label: 'Body Muted Text Color', type: 'color', default: '#8896a6' },
      { key: '--window-card-bg', label: 'Body Inner Cards Fill', type: 'color', default: '#FFFFFF' },
      { key: '--window-card-border', label: 'Body Inner Cards Border', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--window-accent', label: 'Window Accent Color', type: 'color', default: '#FCC676' },

      // === Window Resizers & Corner Handles ===
      { key: '--window-resize-handle-color', label: 'Resize Border Handle Highlight (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.25)' },
      { key: '--window-resize-handle-hover-color', label: 'Resize Border Handle Highlight (Hover / Dragging)', type: 'color', default: '#FCC676' },
      { key: '--window-resize-corner-bg', label: 'Resize Corner Grip Fill (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.4)' },
      { key: '--window-resize-corner-hover-bg', label: 'Resize Corner Grip Fill (Hover / Dragging)', type: 'color', default: '#FCC676' },

      // === Window Session Chip Component (Head-to-Toe) ===
      { key: '--session-chip-bg', label: 'Session Chip Fill / Background', type: 'color', default: 'rgba(255, 255, 255, 0.95)' },
      { key: '--session-chip-border', label: 'Session Chip Border Color', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--session-chip-radius', label: 'Session Chip Corner Radius', type: 'text', default: '4px' },
      { key: '--session-chip-label-color', label: 'Session Chip Label Text (dt)', type: 'color', default: '#8896a6' },
      { key: '--session-chip-value-color', label: 'Session Chip Value Text (dd)', type: 'color', default: '#131e2a' },
      { key: '--session-chip-btn-bg', label: 'Session Chip Action Button Fill (Idle)', type: 'color', default: 'transparent' },
      { key: '--session-chip-btn-border', label: 'Session Chip Action Button Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--session-chip-btn-icon', label: 'Session Chip Action Button Icon (Idle)', type: 'color', default: '#8896a6' },
      { key: '--session-chip-btn-hover-bg', label: 'Session Chip Action Button Fill (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.25)' },
      { key: '--session-chip-btn-hover-border', label: 'Session Chip Action Button Border (Hover)', type: 'color', default: '#FCC676' },
      { key: '--session-chip-btn-hover-icon', label: 'Session Chip Action Button Icon (Hover)', type: 'color', default: '#131e2a' },

      // === Window Workflow Step Indicator Component (Head-to-Toe) ===
      { key: '--step-label-number-bg', label: 'Step Number Fill / Background', type: 'color', default: 'linear-gradient(180deg, #FCC676 0%, #e5a845 100%)' },
      { key: '--step-label-number-border', label: 'Step Number Border Color', type: 'color', default: '#FCC676' },
      { key: '--step-label-number-text', label: 'Step Number Text Color', type: 'color', default: '#131e2a' },
      { key: '--step-label-title-color', label: 'Step Title Text Color (strong)', type: 'color', default: '#131e2a' },
      { key: '--step-label-desc-color', label: 'Step Description Text Color (small)', type: 'color', default: '#4a5568' },

      // === Window Mode Grid Option Cards Component (Head-to-Toe) ===
      // Idle State
      { key: '--mode-grid-btn-bg', label: 'Mode Card Background (Idle)', type: 'color', default: '#FFFFFF' },
      { key: '--mode-grid-btn-border', label: 'Mode Card Border (Idle)', type: 'color', default: 'rgba(174, 135, 79, 0.35)' },
      { key: '--mode-grid-btn-shadow', label: 'Mode Card Shadow (Idle)', type: 'text', default: 'none' },
      { key: '--mode-grid-btn-icon', label: 'Mode Card Icon Color (Idle)', type: 'color', default: '#8896a6' },
      { key: '--mode-grid-btn-title-color', label: 'Mode Card Title Text Color (Idle)', type: 'color', default: '#131e2a' },
      { key: '--mode-grid-btn-desc-color', label: 'Mode Card Description Text Color (Idle)', type: 'color', default: '#4a5568' },

      // Hover State
      { key: '--mode-grid-btn-hover-bg', label: 'Mode Card Background (Hover)', type: 'color', default: 'rgba(252, 198, 118, 0.12)' },
      { key: '--mode-grid-btn-hover-border', label: 'Mode Card Border (Hover)', type: 'color', default: 'rgba(174, 135, 79, 0.55)' },
      { key: '--mode-grid-btn-hover-shadow', label: 'Mode Card Shadow (Hover)', type: 'text', default: '0 4px 12px rgba(0, 0, 0, 0.08)' },
      { key: '--mode-grid-btn-hover-icon', label: 'Mode Card Icon Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--mode-grid-btn-hover-title-color', label: 'Mode Card Title Text Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--mode-grid-btn-hover-desc-color', label: 'Mode Card Description Text Color (Hover)', type: 'color', default: '#131e2a' },

      // Selected State
      { key: '--mode-grid-btn-active-bg', label: 'Mode Card Background (Selected)', type: 'color', default: 'rgba(252, 198, 118, 0.22)' },
      { key: '--mode-grid-btn-active-border', label: 'Mode Card Border (Selected)', type: 'color', default: '#FCC676' },
      { key: '--mode-grid-btn-active-shadow', label: 'Mode Card Shadow (Selected)', type: 'text', default: '0 0 0 1px #FCC676, 0 6px 16px rgba(252, 198, 118, 0.25)' },
      { key: '--mode-grid-btn-active-icon', label: 'Mode Card Icon Color (Selected)', type: 'color', default: '#131e2a' },
      { key: '--mode-grid-btn-active-title-color', label: 'Mode Card Title Text Color (Selected)', type: 'color', default: '#131e2a' },
      { key: '--mode-grid-btn-active-desc-color', label: 'Mode Card Description Text Color (Selected)', type: 'color', default: '#131e2a' },

      // === Choose Step Customization ===
      { key: '--source-choose-step-bg', label: 'Choose Step Background (source_window_choose_step)', type: 'color', default: 'transparent' },
      { key: '--window-card-subtext-color', label: 'Card Sub-text Color (e.g. "Import, search, or load data...")', type: 'color', default: '#4a5568' },
      { key: '--window-card-hover-subtext-color', label: 'Card Sub-text Color (Hover)', type: 'color', default: '#131e2a' },
      { key: '--window-card-active-subtext-color', label: 'Card Sub-text Color (Selected)', type: 'color', default: '#131e2a' },
    ],
  },
  {
    id: 'right_context',
    name: '📋 Right Side — Context Panel',
    description: 'Isolated to the right sidebar: tabs, inspector, chat. No effect on launcher or center.',
    tokens: [
      { key: '--linkx-tab-bg', label: 'Tab Strip BG', type: 'color', default: 'rgba(246, 247, 248, 0.92)' },
      { key: '--linkx-tab-border', label: 'Tab Dividers', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--linkx-tab-active-bg', label: 'Active Tab BG', type: 'color', default: '#131e2a' },
      { key: '--linkx-tab-active-text', label: 'Active Tab Text', type: 'color', default: '#FCC676' },
      { key: '--context-text', label: 'Text Color', type: 'color', default: '#131e2a' },
      { key: '--context-text-secondary', label: 'Secondary Text', type: 'color', default: '#7f5523' },
      { key: '--context-text-muted', label: 'Muted Text', type: 'color', default: '#ae874f' },
      { key: '--context-accent', label: 'Accent Color', type: 'color', default: '#FCC676' },
      { key: '--context-highlight', label: 'Highlight Fill', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--context-cta-bg', label: 'Button Background', type: 'color', default: '#131e2a' },
      { key: '--context-cta-text', label: 'Button Text', type: 'color', default: '#f6efea' },
      { key: '--context-cta-border', label: 'Button Border', type: 'color', default: '#ae874f' },
    ],
  },
  {
    id: 'bottom_dock',
    name: '📌 Bottom — Window Dock',
    description: 'Isolated to the bottom dock bar: tabs, overview menu, docked panel.',
    tokens: [
      { key: '--linkx-dock-header-bg', label: 'Dock Bar BG', type: 'color', default: 'rgba(19, 30, 42, 0.9)' },
      { key: '--linkx-dock-tab-bg', label: 'Dock Tab BG', type: 'color', default: '#131e2a' },
      { key: '--dock-dock-active', label: 'Active Tab BG', type: 'color', default: 'rgba(252, 198, 118, 0.15)' },
      { key: '--primary-action-text', label: 'Dock Action Text', type: 'color', default: '#FCC676' },
      { key: '--dock-text', label: 'Text Color', type: 'color', default: '#131e2a' },
      { key: '--dock-text-secondary', label: 'Secondary Text', type: 'color', default: '#7f5523' },
      { key: '--dock-text-muted', label: 'Muted Text', type: 'color', default: '#ae874f' },
      { key: '--dock-accent', label: 'Accent Color', type: 'color', default: '#FCC676' },
      { key: '--dock-highlight', label: 'Highlight Fill', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--dock-card-bg', label: 'Card Background', type: 'color', default: '#FFFFFF' },
      { key: '--dock-separator', label: 'Separator Line', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--dock-danger-bg', label: 'Close Button BG', type: 'color', default: 'rgba(185, 28, 28, 0.18)' },
    ],
  },
  {
    id: 'source_window',
    name: '📂 Source Window Content',
    description: 'Isolated to source window internals: file browser, tables, toolbars.',
    tokens: [
      { key: '--source-text', label: 'Text Color', type: 'color', default: '#131e2a' },
      { key: '--source-text-secondary', label: 'Secondary Text', type: 'color', default: '#7f5523' },
      { key: '--source-text-muted', label: 'Muted Text', type: 'color', default: '#ae874f' },
      { key: '--source-text-subtle', label: 'Subtle Text', type: 'color', default: 'rgba(127, 85, 35, 0.8)' },
      { key: '--source-accent', label: 'Accent Color', type: 'color', default: '#FCC676' },
      { key: '--source-card-bg', label: 'Card Background', type: 'color', default: '#FFFFFF' },
      { key: '--source-card-border', label: 'Card Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--source-highlight', label: 'Highlight Fill', type: 'color', default: 'rgba(174, 135, 79, 0.12)' },
      { key: '--source-separator', label: 'Separator Line', type: 'color', default: 'rgba(174, 135, 79, 0.3)' },
      { key: '--source-cta-bg', label: 'Button Background', type: 'color', default: '#131e2a' },
      { key: '--source-cta-text', label: 'Button Text', type: 'color', default: '#f6efea' },
    ],
  },
  {
    id: 'settings_window',
    name: '⚙️ Settings Window Content',
    description: 'Isolated to settings panels: forms, labels, inputs, buttons.',
    tokens: [
      { key: '--settings-text', label: 'Text Color', type: 'color', default: '#131e2a' },
      { key: '--settings-text-secondary', label: 'Secondary Text', type: 'color', default: '#7f5523' },
      { key: '--settings-text-muted', label: 'Muted Text', type: 'color', default: '#ae874f' },
      { key: '--settings-accent', label: 'Accent Color', type: 'color', default: '#FCC676' },
      { key: '--settings-card-bg', label: 'Card Background', type: 'color', default: '#FFFFFF' },
      { key: '--settings-card-border', label: 'Card Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--settings-cta-bg', label: 'Button Background', type: 'color', default: '#131e2a' },
      { key: '--settings-border', label: 'Section Border', type: 'color', default: 'rgba(174, 135, 79, 0.45)' },
      { key: '--linkx-form-label', label: 'Form Labels', type: 'color', default: '#7f5523' },
      { key: '--linkx-link-text', label: 'Link Text', type: 'color', default: '#ae874f' },
      { key: '--settings-danger-bg', label: 'Danger Background', type: 'color', default: 'rgba(185, 28, 28, 0.18)' },
      { key: '--settings-danger-text', label: 'Danger Text', type: 'color', default: '#b91c1c' },
    ],
  },
];
